name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  some-input:  # id of input
    description: 'something to print'
    required: true
    default: 'goose'
outputs:
  some-output: # id of output
    description: 'some random uuid'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.some-input }}
