
name: context

on:
  workflow_dispatch:

jobs:
  context_job:
    runs-on: ubuntu-latest
    name: A job to test stuff
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: get context
        run: echo "${{ toJSON(github) }}"
