name: goose

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test stuff
    steps:
      - name: go main custom step
        uses: loosebazooka/docker-go-ghaction@1
        id: hello
        with:
          some-input: 'goose'
      # Use the output from the `hello` step
      - name: view output
        run: echo "uuid - ${{ steps.hello.outputs.some-output }}"
